"""
Trustworthiness analysis for adversarial ML-NIDS evaluation.

Measures:
    - Brier score
    - Expected Calibration Error (ECE)
    - confidence statistics
    - confidence drop
    - prediction changes

Conditions:
    - Clean
    - Conventional FGSM
    - Conventional PGD
    - Constraint-aware FGSM
    - Constraint-aware PGD

The analysis uses the saved adversarial examples generated by the
attack experiments. If adversarial examples were not previously
saved, this script reconstructs them using the exact same settings.
"""

from pathlib import Path
import importlib.util
import json
import numpy as np
import pandas as pd
import joblib


# ============================================================
# PATHS
# ============================================================

ROOT = Path(__file__).resolve().parents[2]

X_TEST_PATH = ROOT / "data/processed/unsw_X_test.csv"
Y_TEST_PATH = ROOT / "data/processed/unsw_y_test.csv"

MODEL_PATH = ROOT / "results/models/mlp_clean.joblib"

SAMPLE_PATH = (
    ROOT /
    "results/attacks/"
    "conventional_attack_sample_indices.csv"
)

CONVENTIONAL_RESULTS_PATH = (
    ROOT /
    "results/attacks/"
    "conventional_attack_results.csv"
)

CONSTRAINT_RESULTS_PATH = (
    ROOT /
    "results/attacks/"
    "constraint_aware_attack_results_mlp.csv"
)

ATTACK_MODULE_PATH = (
    ROOT /
    "src/attacks/"
    "06_conventional_attacks.py"
)

CONSTRAINT_MODULE_PATH = (
    ROOT /
    "src/attacks/"
    "11_constraint_aware_attacks.py"
)

OUTPUT_DIR = ROOT / "results/analysis"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# SETTINGS
# ============================================================

SEED = 42

EPSILONS = [0.05, 0.10, 0.20]

PGD_STEPS = 10


# ============================================================
# LOAD CONVENTIONAL ATTACK MODULE
# ============================================================

spec = importlib.util.spec_from_file_location(
    "conventional_attacks",
    ATTACK_MODULE_PATH
)

conventional_attacks = importlib.util.module_from_spec(spec)
spec.loader.exec_module(conventional_attacks)


# ============================================================
# LOAD DATA
# ============================================================

print("=" * 70)
print("TRUSTWORTHINESS ANALYSIS")
print("=" * 70)

X_test = pd.read_csv(X_TEST_PATH).values
y_test = pd.read_csv(Y_TEST_PATH).values.ravel()

model = joblib.load(MODEL_PATH)

sample_indices = pd.read_csv(
    SAMPLE_PATH
)["test_index"].values

X_attack = X_test[sample_indices].copy()
y_attack = y_test[sample_indices].copy()

print(f"Test samples: {len(X_test)}")
print(f"Analysis samples: {len(X_attack)}")
print(f"Processed features: {X_attack.shape[1]}")


# ============================================================
# FEATURE MASK
# ============================================================

feature_mask = conventional_attacks.get_numerical_feature_mask(
    n_features=X_test.shape[1]
)


# ============================================================
# LOAD CONSTRAINT INFORMATION
# ============================================================

with open(
    ROOT / "results/logs/unsw_preprocessing_metadata.json",
    "r",
    encoding="utf-8"
) as f:
    metadata = json.load(f)

preprocessor = joblib.load(
    ROOT / "data/processed/unsw_preprocessor.joblib"
)

numerical_features = metadata["numerical_features"]

feature_names = [
    f"numerical__{name}"
    for name in numerical_features
]

encoder = preprocessor.named_transformers_["categorical"]

encoded_feature_names = encoder.get_feature_names_out(
    metadata["categorical_features"]
)

feature_names.extend(
    f"categorical__{name}"
    for name in encoded_feature_names
)

constraint_mask = feature_mask.copy()

BINARY_FIXED = {
    "numerical__is_ftp_login",
    "numerical__is_sm_ips_ports",
}

for i, name in enumerate(feature_names):

    if name in BINARY_FIXED:
        constraint_mask[i] = False

    if name.startswith("numerical__ct_"):
        constraint_mask[i] = False

    if name.startswith("categorical__"):
        constraint_mask[i] = False


# ============================================================
# TRAINING BOUNDS
# ============================================================

X_train = pd.read_csv(
    ROOT / "data/processed/unsw_X_train.csv"
).values

train_lower = np.min(
    X_train,
    axis=0
)

train_upper = np.max(
    X_train,
    axis=0
)


# ============================================================
# CALIBRATION FUNCTIONS
# ============================================================

def brier_score(y_true, probabilities):
    """
    Mean squared error between predicted probability
    and observed binary outcome.
    """

    return np.mean(
        (probabilities - y_true) ** 2
    )


def expected_calibration_error(
    y_true,
    probabilities,
    n_bins=10,
):
    """
    Expected Calibration Error using equal-width
    probability bins.
    """

    y_true = np.asarray(y_true)
    probabilities = np.asarray(probabilities)

    bins = np.linspace(
        0.0,
        1.0,
        n_bins + 1
    )

    ece = 0.0

    bin_records = []

    for i in range(n_bins):

        if i == n_bins - 1:
            mask = (
                (probabilities >= bins[i]) &
                (probabilities <= bins[i + 1])
            )
        else:
            mask = (
                (probabilities >= bins[i]) &
                (probabilities < bins[i + 1])
            )

        count = np.sum(mask)

        if count == 0:
            continue

        accuracy = np.mean(
            y_true[mask]
        )

        confidence = np.mean(
            probabilities[mask]
        )

        weight = count / len(y_true)

        calibration_gap = abs(
            accuracy - confidence
        )

        ece += (
            weight *
            calibration_gap
        )

        bin_records.append({
            "bin": i,
            "lower": bins[i],
            "upper": bins[i + 1],
            "count": int(count),
            "accuracy": accuracy,
            "confidence": confidence,
            "gap": calibration_gap,
        })

    return ece, pd.DataFrame(bin_records)


# ============================================================
# CONSTRAINT APPLICATION
# ============================================================

def apply_constraints(
    X_clean,
    X_candidate,
):
    """
    Restore fixed features and enforce training-derived bounds.
    """

    X_constrained = X_candidate.copy()

    # Fixed features remain identical to clean input.
    X_constrained[:, ~constraint_mask] = (
        X_clean[:, ~constraint_mask]
    )

    # Eligible features remain within empirical training bounds.
    for i in np.where(constraint_mask)[0]:

        X_constrained[:, i] = np.clip(
            X_constrained[:, i],
            train_lower[i],
            train_upper[i],
        )

    return X_constrained


# ============================================================
# ATTACK RECONSTRUCTION
# ============================================================

def generate_attack(
    attack_type,
    epsilon,
):
    """
    Reconstruct an adversarial condition using the exact
    experimental settings.
    """

    if attack_type == "FGSM":

        X_adv = conventional_attacks.fgsm_attack_mlp(
            model=model,
            X=X_attack,
            y=y_attack,
            epsilon=epsilon,
            feature_mask=feature_mask,
        )

        return X_adv

    if attack_type == "PGD":

        X_adv = conventional_attacks.pgd_attack_mlp(
            model=model,
            X=X_attack,
            y=y_attack,
            epsilon=epsilon,
            step_size=epsilon / 4,
            num_steps=PGD_STEPS,
            feature_mask=feature_mask,
        )

        return X_adv

    if attack_type == "constraint_aware_FGSM":

        X_adv = conventional_attacks.fgsm_attack_mlp(
            model=model,
            X=X_attack,
            y=y_attack,
            epsilon=epsilon,
            feature_mask=constraint_mask,
        )

        return apply_constraints(
            X_attack,
            X_adv
        )

    if attack_type == "constraint_aware_PGD":

        lower = np.maximum(
            X_attack - epsilon,
            train_lower
        )

        upper = np.minimum(
            X_attack + epsilon,
            train_upper
        )

        X_adv = conventional_attacks.pgd_attack_mlp(
            model=model,
            X=X_attack,
            y=y_attack,
            epsilon=epsilon,
            step_size=epsilon / 4,
            num_steps=PGD_STEPS,
            feature_mask=constraint_mask,
            lower_bounds=lower,
            upper_bounds=upper,
        )

        return apply_constraints(
            X_attack,
            X_adv
        )

    raise ValueError(
        f"Unknown attack type: {attack_type}"
    )


# ============================================================
# PREDICTION HELPER
# ============================================================

def get_probability(X):
    return conventional_attacks.get_positive_class_probability(
        model,
        X
    )


# ============================================================
# CLEAN CONDITION
# ============================================================

clean_probability = get_probability(
    X_attack
)

clean_prediction = (
    clean_probability >= 0.5
).astype(int)


# ============================================================
# ANALYSIS FUNCTION
# ============================================================

def analyze_condition(
    condition,
    epsilon,
    X_adv,
):
    """
    Calculate trustworthiness metrics for one condition.
    """

    attacked_probability = get_probability(
        X_adv
    )

    attacked_prediction = (
        attacked_probability >= 0.5
    ).astype(int)

    successful_evasion = (
        (y_attack == 1) &
        (clean_prediction == 1) &
        (attacked_prediction == 0)
    )

    confidence_drop = (
        clean_probability -
        attacked_probability
    )

    clean_brier = brier_score(
        y_attack,
        clean_probability
    )

    attacked_brier = brier_score(
        y_attack,
        attacked_probability
    )

    clean_ece, _ = expected_calibration_error(
        y_attack,
        clean_probability
    )

    attacked_ece, _ = expected_calibration_error(
        y_attack,
        attacked_probability
    )

    prediction_changes = np.sum(
        clean_prediction != attacked_prediction
    )

    result = {
        "model": "mlp",
        "condition": condition,
        "epsilon": epsilon,
        "samples": len(y_attack),

        "successful_evasions": int(
            successful_evasion.sum()
        ),

        "attack_success_rate": (
            successful_evasion.sum() /
            len(y_attack)
        ),

        "mean_clean_probability": (
            np.mean(clean_probability)
        ),

        "mean_attacked_probability": (
            np.mean(attacked_probability)
        ),

        "mean_confidence_drop": (
            np.mean(confidence_drop)
        ),

        "median_confidence_drop": (
            np.median(confidence_drop)
        ),

        "clean_brier_score": clean_brier,

        "attacked_brier_score": attacked_brier,

        "brier_score_change": (
            attacked_brier -
            clean_brier
        ),

        "clean_ece": clean_ece,

        "attacked_ece": attacked_ece,

        "ece_change": (
            attacked_ece -
            clean_ece
        ),

        "prediction_changes": int(
            prediction_changes
        ),

        "prediction_change_rate": (
            prediction_changes /
            len(y_attack)
        ),
    }

    return result


# ============================================================
# CLEAN BASELINE
# ============================================================

clean_ece, clean_bins = (
    expected_calibration_error(
        y_attack,
        clean_probability
    )
)

clean_result = {
    "model": "mlp",
    "condition": "clean",
    "epsilon": 0.0,
    "samples": len(y_attack),

    "successful_evasions": 0,
    "attack_success_rate": 0.0,

    "mean_clean_probability": (
        np.mean(clean_probability)
    ),

    "mean_attacked_probability": (
        np.mean(clean_probability)
    ),

    "mean_confidence_drop": 0.0,
    "median_confidence_drop": 0.0,

    "clean_brier_score": (
        brier_score(
            y_attack,
            clean_probability
        )
    ),

    "attacked_brier_score": (
        brier_score(
            y_attack,
            clean_probability
        )
    ),

    "brier_score_change": 0.0,

    "clean_ece": clean_ece,
    "attacked_ece": clean_ece,
    "ece_change": 0.0,

    "prediction_changes": 0,
    "prediction_change_rate": 0.0,
}

results = [clean_result]


# ============================================================
# RUN ALL ATTACK CONDITIONS
# ============================================================

conditions = [
    ("FGSM", "conventional"),
    ("PGD", "conventional"),
    ("constraint_aware_FGSM", "constraint_aware"),
    ("constraint_aware_PGD", "constraint_aware"),
]


for attack_type, category in conditions:

    for epsilon in EPSILONS:

        print("\n" + "=" * 70)
        print(
            f"{attack_type} | "
            f"epsilon={epsilon}"
        )
        print("=" * 70)

        X_adv = generate_attack(
            attack_type,
            epsilon
        )

        result = analyze_condition(
            condition=attack_type,
            epsilon=epsilon,
            X_adv=X_adv
        )

        results.append(result)

        print(
            f"ASR: "
            f"{result['attack_success_rate']:.4f}"
        )

        print(
            f"Mean confidence drop: "
            f"{result['mean_confidence_drop']:.4f}"
        )

        print(
            f"Brier: "
            f"{result['clean_brier_score']:.4f} "
            f"-> "
            f"{result['attacked_brier_score']:.4f}"
        )

        print(
            f"ECE: "
            f"{result['clean_ece']:.4f} "
            f"-> "
            f"{result['attacked_ece']:.4f}"
        )


# ============================================================
# SAVE SUMMARY
# ============================================================

results_df = pd.DataFrame(results)

summary_path = (
    OUTPUT_DIR /
    "trustworthiness_results_mlp.csv"
)

results_df.to_csv(
    summary_path,
    index=False
)


# ============================================================
# SAVE CLEAN CALIBRATION BINS
# ============================================================

clean_bins_path = (
    OUTPUT_DIR /
    "clean_calibration_bins_mlp.csv"
)

clean_bins.to_csv(
    clean_bins_path,
    index=False
)


# ============================================================
# SAVE METADATA
# ============================================================

analysis_metadata = {
    "model": "mlp",
    "dataset": "UNSW-NB15",
    "seed": SEED,
    "samples": len(y_attack),
    "ece_bins": 10,
    "brier_score": (
        "mean squared probability error"
    ),
    "constraint_type": (
        "constraint-aware feature-space"
    ),
    "host_space_attack": False,
}

metadata_path = (
    OUTPUT_DIR /
    "trustworthiness_analysis_metadata_mlp.json"
)

with open(
    metadata_path,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        analysis_metadata,
        f,
        indent=2
    )


# ============================================================
# FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("TRUSTWORTHINESS ANALYSIS COMPLETE")
print("=" * 70)

print(
    results_df[
        [
            "condition",
            "epsilon",
            "attack_success_rate",
            "mean_confidence_drop",
            "clean_brier_score",
            "attacked_brier_score",
            "clean_ece",
            "attacked_ece",
            "ece_change",
        ]
    ].to_string(index=False)
)

print("\nResults:")
print(summary_path)

print("\nCalibration bins:")
print(clean_bins_path)

print("\nMetadata:")
print(metadata_path)